### ISSUE TITLE
SWAGGER 도입

### ISSUE THREAD

**Issue by J-Jaeh** [allnight5/final-8-team-project#104]
API명세 공유를 위한 SWAGGER도입

**Comment by J-Jaeh** [comment]
선택에 있어서 
springdoc vs springfox 라이브러리 고민

springdoc 선택 공식문서가 읽기 편하고 api 그룹핑 설정이 간단 그리고 좀 더 활발한 업데이트 진행되고있음

**Comment by J-Jaeh** [comment]
![image](https://user-images.githubusercontent.com/117059721/230934788-3f3d94ec-d694-496a-8f1a-7723d9b8291f.png)
공식문서에서 스프링부트 3.0 이상부터는...
springdoc 2.0이상 버전을 사용하라고 합니다..전이것도 모르고 ...ㅠ_ㅠ

**Comment by J-Jaeh** [comment]
## 활발한 업데이트 비교

> 선택에 있어서 springdoc vs springfox 라이브러리 고민
> 
> springdoc 선택 공식문서가 읽기 편하고 api 그룹핑 설정이 간단 그리고 좀더 활발한 업데이트 진행되고있음

![image](https://user-images.githubusercontent.com/117059721/230938498-79905879-ce9b-4789-8bf6-e14f8bf6b314.png)

최근까지 활발한 커밋  (springdoc)


---

![image](https://user-images.githubusercontent.com/117059721/230938650-66500080-6a14-4351-a448-4e234296b8b7.png)

3년전이 마지막 커밋 (springfox)

**Comment by J-Jaeh** [comment]
> ![image](https://user-images.githubusercontent.com/117059721/230934788-3f3d94ec-d694-496a-8f1a-7723d9b8291f.png) 공식문서에서 스프링부트 3.0 이상부터는... springdoc 2.0이상 버전을 사용하라고 합니다..전이것도 모르고 ...ㅠ_ㅠ


``` java
  implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.2'
```

**Comment by J-Jaeh** [comment]
### 웹 시큐리티 관련 오류 

```java
   @Bean
    public WebSecurityCustomizer webSecurityCustomizer() {
        // h2-console 사용 및 resources 접근 허용 설정
        return (web) -> web.ignoring()
                .requestMatchers(PathRequest.toH2Console())
                .requestMatchers(PathRequest.toStaticResources().atCommonLocations())
                .requestMatchers("/v3/api-docs/**", "/swagger-ui.html", "/swagger-ui/**");
    }
```

---
오류 해결 했고

기본 swagger ui 나오는 중입니다.


![image](https://user-images.githubusercontent.com/117059721/230951834-200d2828-e150-4fc2-ac03-6ba0050cc646.png)

---

[추가공부](https://resilient-923.tistory.com/414)

**Comment by J-Jaeh** [comment]
api별로 분류했습니다
![스웨거분류](https://user-images.githubusercontent.com/117059721/231652989-23118ef0-4904-4b41-9df1-234df9a931ee.png)

**Comment by wonizizi89** [comment]
>.< 저희가 작성한 api 보다 훨씬!!! 좋네요 . 수고 하셨습니다.

**Comment by J-Jaeh** [comment]
###  완성 되면 한번 정리해서 올리겠습니다
---
<details><summary>불필요한 responses 제거</summary>
<p>
여기 밑에 400 403 404 가 디폴트로 잡혀있는거 가독성이 불편해서 제거 

![image](https://user-images.githubusercontent.com/117059721/232315013-5dc5ca29-7aee-4e31-9504-1ebc082d296a.png)

yml 파일 설정해주자 ..!

```java
springdoc:
  override-with-generic-response: false
```

따로 yml파일 관리 해주고 싶은데 인식을 못해서 application.yml에 추가 해줬습니다


적용 후 
![image](https://user-images.githubusercontent.com/117059721/232315251-70a82fd2-909f-45f1-aa20-df5ec5048a45.png)

</p>
</details> 



---

<details><summary>response 커스텀</summary>


<p>

기본적인 커스텀입니다
이렇게 하면  스웨거에 메소드의 이름과 설명 , 각각 에러코드를 임의로 설정 가능합니다
![image](https://user-images.githubusercontent.com/117059721/232327870-928c6a86-39bd-47f2-8b0c-adb86dcdbf8f.png)

적용 후

![image](https://user-images.githubusercontent.com/117059721/232328143-069e8370-d592-47c4-b03b-fc14e2c01ddc.png)

![image](https://user-images.githubusercontent.com/117059721/232328158-1aa5fa64-3d6b-4eda-86c7-e4b201f91428.png)

</p>
</details> 


<details><summary>스키마적용</summary>
<p>
반환되는 값이 뭔지 좀 더 상세하게 적는 것 입니다.  
<br>
<br>
적용전  
<br>
<br>


![image](https://user-images.githubusercontent.com/117059721/232330468-66823cc4-bb7e-4b1b-adea-f5bfd130c7bc.png)


@Schema 적용
> 해당하는 dto나 반환값에 달아주면 됩니다.

```java
    @Getter
    @NoArgsConstructor(access = AccessLevel.PROTECTED)
    @Schema(description = "게시글 조회시 반환 dto")
    public static class Result<T> {
        @Schema(description = "페이지 번호", example = "2")
        private int page;
        @Schema(description = "총 가지고온 게시글의 수", example = "6")
        private int totalCount;

        @Schema(description = "한페이지에 표현할 게시글 수 ", example = "3")
        private int countPage;
        @Schema(description = "총 만들어진 페이지 수  ", example = "2")
        private int totalPage;

        @Schema(description = "게시글 ", example = "{제목,작성일자,내용,댓글,대댓글..등}")
        private T data;

        public Result(int page, int totalCount, int countPage, int totalPage, T data) {
            this.page = page;
            this.totalCount = totalCount;
            this.countPage = countPage;
            this.totalPage = totalPage;
            this.data = data;
        }
    }
```
<br>
<br>
적용 후 

![image](https://user-images.githubusercontent.com/117059721/232330347-12206741-f4ea-443f-b026-842a2a556ff8.png)
![image](https://user-images.githubusercontent.com/117059721/232330413-49a4e0ff-7f37-4b82-8051-f699723ed530.png)

</p>
</details>
