### ISSUE TITLE
로컬시간과 서버시간 불일치.

### ISSUE THREAD

**Issue by J-Jaeh** [allnight5/final-8-team-project#50]
![image](https://user-images.githubusercontent.com/117059721/223625380-10919fcf-dfa1-4670-85d4-61de04097ff6.png)

서버시간이 9시간 느린듯합니다!

**Comment by wonizizi89** [comment]
네 의견 감사합니다. 제가 다시 수정 하도록 하겠습니다 .

**Comment by wonizizi89** [comment]
두가지 해결 방법을 찾았습니다. 한가지는 백엔드에서 
DateFormatConfiguration 로 하는 방법이 있지만 
글로벌 시간을 설정하기 위해선 프론트에서 처리 해야된다고 생각되어 방법만 알고 구현은 하지 않기로 의견조율했습니다. 

@Configuration
public class DateFormatConfiguration {

  private static final String dateFormat = "yyyy-MM-dd";
  private static final String datetimeFormat = "yyyy-MM-dd HH:mm";

  @Bean
  public Jackson2ObjectMapperBuilderCustomizer jackson2ObjectMapperBuilderCustomizer(){
    return jacksonObjectMapperBuilder -> {
      jacksonObjectMapperBuilder.timeZone(TimeZone.getTimeZone("Asia/Seoul"));
      jacksonObjectMapperBuilder.simpleDateFormat(datetimeFormat);
      jacksonObjectMapperBuilder.serializers(new LocalDateSerializer(DateTimeFormatter.ofPattern(dateFormat)));
      jacksonObjectMapperBuilder.serializers(new LocalDateTimeSerializer(DateTimeFormatter.ofPattern(datetimeFormat)));
    };
  }
}
