### ISSUE TITLE
application.yml 수정이 필요할 것 같습니다. 

### ISSUE THREAD

**Issue by wonizizi89** [allnight5/final-8-team-project#72]
application.yml 이 현재 전체가 gitignore되어 있어 ci/cd 때 application.yml  파일 찾지 못해 테스트에서 오류가 나는 부분이 있습니다. 그리고 전체 application.yml 통일을 위해서 민간한 정보를 별도 분리한 yml 파일을 만드는 것이 좋을 거 같은데 어떠세요???

**Comment by allnight5** [comment]
만들수 있다면 좋을것 같아요

**Comment by wonizizi89** [comment]
수정 없이도 ci , cd 구축하는 방법을 알게 되어 우선 ^^ 그대로 두겠습니다.
