### ISSUE TITLE
Cache 적용완료

### ISSUE THREAD

**Issue by allnight5** [allnight5/final-8-team-project#90]

**Comment by allnight5** [comment]
rediscofing를 만들어둔 곳에서
@EnableRedisRepositories
@EnableCaching
이 두가지를 붙여서 처리할수있으나

레디스의 캐싱마다 다른 방식의 직렬화를 처리해주고 싶다면 
[레디스의 캐싱마다 다른방식의 직렬화](https://github.com/Gymlike/final-8-team-project/blob/e12ba9e2db98e27703142784515349e44b8cc7fc/src/main/java/com/team/final8teamproject/redis/cache/CacheConfiguration.java#L21)

이렇게 만들어줘야하는 불편함이 생길수도있다. 
두개를 같이 쓰면 되지만 따로 작성해서 해보았다.
두개를 같이쓴다면 redisconfig에 적용된 것으로 되지만
cacheNames에 cacheNames로 적용된 캐시이름이
내가 따로 만든 RedisCacheManager 에 있다면 RedisCacheManager 의 형태로 된다. 
하지만 이름이 충돌하게 되면 오류가 나니 두가지를 같이 사용할때는 이름이 충돌하지 않도록 조심해야하며
어노테이션으로 사용시 cacheNames아닌 value로 사용하면된다.
 cacheNames는 여러개의 이름이 사용가능하지만 value는 하나의 이름만 사용이 가능하다.

    @Cacheable(cacheNames = CacheNames.USERBYUSERNAME, key="'login'+#p0", unless="#result==null")
    Optional<BaseEntity> findByUsername(String username);
로그인
---
![캐시적용](https://user-images.githubusercontent.com/45612782/229405719-d2dcdd79-c7e6-49e0-858e-4774139cd959.JPG)
>key에 'login'을 붙인이유는 username이 null값으로 들어왔을때 오류가 발생하기 때문에 이것을 잡고자 넣었고
#username이 아닌 #p0를 넣은이유는 #username은 null값을 가져올때까지 있기 때문에 
#p0로 파라미터 첫번째 값인 username을 가져오도록 하였다. #username과 동작은 같지만 방법은 다른것이다.
 findByUsernameAndEmail(String username, String email);
이렇게 했을때 #p1을 하면 email을 가져오게 된다 p의 숫자에 따라서 파라미터를 순서대로 가져오는데 0부터 시작한다.

**인덱스와 캐시를 적용하기 전이다.**
![인덱스 적용 하기 전](https://user-images.githubusercontent.com/45612782/229405828-d9b3cb7a-ff37-4f5e-abbc-365add6cacf0.JPG)


**캐싱 적용후 로그인이다.**
![캐시 적용후](https://user-images.githubusercontent.com/45612782/229405897-cea3c73a-1385-4991-b257-f0d4d8bf20d2.JPG)

글작성
-------------------- 
**글작성을 적용하기 전이다.**
![적용전](https://user-images.githubusercontent.com/45612782/229406567-b8f0c0de-fad8-46e6-aeb7-85fbdbee1a00.JPG)

**캐시를 적용하고 나서다**
![캐시가 적용 되었을때 글작성](https://user-images.githubusercontent.com/45612782/229405864-55c1ca44-cdcf-458c-9920-2d68f0ffc1f7.JPG)


**인데스를 적용하고 나서**
**인덱스 적용**
![인덱스 적용하기](https://user-images.githubusercontent.com/45612782/229407305-eed588d9-51de-495f-b6dc-78d2686655fb.JPG)

**인덱스 적용하고 글작성 해보기**
![인덱스를 적용하여 캐시와 같은 속도가 나옴](https://user-images.githubusercontent.com/45612782/229406974-d5882fb8-52c1-423a-ab09-62ac93d7bed2.JPG)


인덱스가 적용되었을때와 캐시가 적용되었을때 속도는 같았다. 향상되는 것은 미미 하였고 인덱스를 username에 적용했을때 보안상 문제가 있었고 그로인하여 제거하기로 하였다.


유저조회
---
**캐시 적용전 유저조회** 
![유저 조회](https://user-images.githubusercontent.com/45612782/229407096-0841c848-9ff0-48c4-9491-8ed80080336f.JPG)


**캐시적용**
![유저 조회 캐싱 적용](https://user-images.githubusercontent.com/45612782/229407386-196adc53-56b2-44cd-a2b0-2a7bc5d856fb.JPG)

**Comment by wonizizi89** [comment]
+_+!! 오오오 캐시 적용후 날개를 달았네요 >.<ㅎㅎ 어려우셨을텐데 ㅎㅎ 넘 수고 하셨어요 !!

**Comment by J-Jaeh** [comment]
캐싱적용 멋집니다..!
