### ISSUE TITLE
redis 기능(서버 부하 테스트) 테스트 1 - apache jmeter

### ISSUE THREAD

**Issue by allnight5** [allnight5/final-8-team-project#98]
## Jmeter 세팅하는 방법 -> [링크](https://velog.io/@allnight5/%EC%8A%A4%ED%94%84%EB%A7%81apache-Jmeter%EC%84%A4%EC%B9%98%EC%99%80-%EC%8B%A4%ED%96%89-%EC%8B%9C%EC%BC%9C%EB%B3%B4%EA%B8%B0)

# 1번 테스트
---
## 조건
쓰레드풀 30개 1초에 400개 캐싱O
---
처음 시작할때 1초간
![초기일때](https://user-images.githubusercontent.com/45612782/230147533-0d9811f4-871b-4d7a-b430-756da087bf5f.JPG)

중간부분
![중간](https://user-images.githubusercontent.com/45612782/230147546-1073e3b4-4315-4ebd-a53d-eb1150dad928.JPG)

갑자기 올라간다.
![값이 튄다](https://user-images.githubusercontent.com/45612782/230147504-651b49b7-a410-4f64-8dcd-d946b1952553.JPG)

음.. 왜그런지 잘 모르겠다. 내 컴퓨터 문제인것 같은데.. 나중에 EC2 서버 열어서 재실험 해봐야겠다.
 

# 2번 테스트
---
## 조건
쓰레드풀 100개 1초에 1000개 캐싱X
---
잘 된다. 하지만. 도커에서 keys *를 입력해서 확인하는 순간 작동이 잠시 멈춘다.
key가 8개밖에 안되는데도 동작이 멈추는 것을 보면. 많은 접속자가 많은 요청을 날릴때 keys *를 하면 오류가 난다는 것을 알았다.
실제 서버에서 할때 도커에 절대 keys *로 확인하지말고 다른 방법을 찾아보자 요청을 멈춰야 다시 살아나는데 계속 요청이 들어온다면 계속 작동 정지가 될 것 으로 예상된다.

처음에 캐싱하기전
---
![100개에 1000개](https://user-images.githubusercontent.com/45612782/230150060-137dfd78-ba90-4897-afbb-88abb79e0c03.JPG)

중간
---
![이상할때](https://user-images.githubusercontent.com/45612782/230150037-3c4cacd2-1bb5-469e-9788-923a08e4bac7.JPG)

잘되었을때
---
![잘됬을때](https://user-images.githubusercontent.com/45612782/230150052-4c887dbf-f7f6-4e15-87f9-f2f924e00ebf.JPG)

선택한 페이지를 가져오는 부분은 많이 캐싱해서 가져가지 못하는 것 같기도 하다.. 컴퓨터 문제인가 로직문제인가..
유저 로그인 부분은 캐싱 이후 일정 시간 이하를 유지한다. 하지만 유저와 요청이 많으니 일정이하로 내려가지 않는다.
이것을 보니 게시판 조회부분이 문제가 있는것 같기도 한데? 어느 부분이 문제인지는 한번 다시 살펴봐야 겠다.

어쨋든 요청이 많을 수록 응답시간이 오래 걸린다는 것을 알았다. 

그런데 Saturation Point 지점 찾지 못했다.
다음에는 지점을 찾을 수 있도록 새로운 시나리오를 작성해 봐야겠다.

**Comment by wonizizi89** [comment]
jmeter 이용한 성능개선 하는 부분 보고 싶었는데 +_+ 효근님 멋집니다.

**Comment by smalldevK** [comment]
👍👍👍👍👍👍👍👍👍👍

**Comment by allnight5** [comment]
보니까.. 유저수를 늘렸어야했는데 루프를 늘렸더군여 흑흑
